### PR TITLE
Update AnalogReadSerial.ino

### PR DESCRIPTION
**Pull request by kengdahl**
Fixed faulty link

### CODE REVIEW

**Review by per1234 — APPROVED** [review]
Looks good, but please, please, please also set up redirects for these URLs. I'm sure thousands of links to the previous URL all over the Internet were broken by the change that caused this to be necessary.

**Comment by ubidefeo** [comment]
@per1234 what are you referring to?
@kengdahl asked me to merge the PR but I don't fully understand which URL redirects you intend here

**Comment by per1234** [comment]
@ubidefeo there was a change to the structure of the documentation content on arduino.cc that changed URLs. Some of the old URLs were not redirected, which was the case with http://www.arduino.cc/en/Tutorial/AnalogReadSerial, which was likely the motivation for this PR.

I see that now http://www.arduino.cc/en/Tutorial/AnalogReadSerial does redirect as it should to the new URL https://www.arduino.cc/en/Tutorial/BuiltInExamples/AnalogReadSerial (thanks!), but I think it's still a good idea to update this URL to point to the new  location of the content to avoid relying on the redirect. The same issue occurs in every single example in this repository.

**Comment by ubidefeo** [comment]
thanks @per1234 , that detail was lost on me.
please @kengdahl , if you can set a task to make sure all URLs in this repo are aligned adding the `/BuiltinExamples` portion of the path.
In the meantime I'll merge this one

**Comment by kengdahl** [comment]
@ubidefeo

**Comment by per1234** [comment]
>I'll do that.

Forget about it. I went ahead and did it. Please review: https://github.com/arduino/arduino-examples/pull/30

**Pull request merged**
